# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amq < Formula
  desc "Agent Message Queue - file-based inter-agent messaging for Claude Code and Codex CLI"
  homepage "https://github.com/avivsinai/agent-message-queue"
  version "0.41.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/avivsinai/agent-message-queue/releases/download/v0.41.1/amq_0.41.1_darwin_amd64.tar.gz"
      sha256 "64e0b71f2a93869f946e012e4df3d59b79bf89127738bdb955bab613c3220892"

      define_method(:install) do
        bin.install "amq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/avivsinai/agent-message-queue/releases/download/v0.41.1/amq_0.41.1_darwin_arm64.tar.gz"
      sha256 "921b708f4be4b8fc37dbb69bc46fc230ee3686518f24a5522bf06c47ab98c774"

      define_method(:install) do
        bin.install "amq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/agent-message-queue/releases/download/v0.41.1/amq_0.41.1_linux_amd64.tar.gz"
      sha256 "9977a3c211a81bb4a9297b05eaed06bb65fe52ed352ca34722dda04468b1129e"
      define_method(:install) do
        bin.install "amq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/agent-message-queue/releases/download/v0.41.1/amq_0.41.1_linux_arm64.tar.gz"
      sha256 "a8afe52cf3cec595ebf10c1c92622bbc158b2d527db0c791a3e604508a5c354e"
      define_method(:install) do
        bin.install "amq"
      end
    end
  end

  test do
    system "#{bin}/amq", "--version"
  end
end
