# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amq < Formula
  desc "Agent Message Queue - file-based inter-agent messaging for Claude Code and Codex CLI"
  homepage "https://github.com/avivsinai/agent-message-queue"
  version "0.60.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/avivsinai/agent-message-queue/releases/download/v0.60.3/amq_0.60.3_darwin_amd64.tar.gz"
      sha256 "59c8f07d3c81eb2f81638574fa9b71986ed793519e8c52117716805c077fc7aa"

      define_method(:install) do
        bin.install "amq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/avivsinai/agent-message-queue/releases/download/v0.60.3/amq_0.60.3_darwin_arm64.tar.gz"
      sha256 "ecacf2c2b8a590c54f6db1c446b1e264242e9841aae71adc885ad4908bec4df1"

      define_method(:install) do
        bin.install "amq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/agent-message-queue/releases/download/v0.60.3/amq_0.60.3_linux_amd64.tar.gz"
      sha256 "e2c6fec7e39ffcf86b7a9039986689997fc60d9d47f0ab59021487ca63706e32"
      define_method(:install) do
        bin.install "amq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/agent-message-queue/releases/download/v0.60.3/amq_0.60.3_linux_arm64.tar.gz"
      sha256 "4d3280ce4e47bed8c414d9f99b08306b779a297c383ad1a409d6d744188e7404"
      define_method(:install) do
        bin.install "amq"
      end
    end
  end

  test do
    system "#{bin}/amq", "--version"
  end
end
