# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BitbucketCli < Formula
  desc "CLI for Bitbucket Cloud - manage repos, PRs, and pipelines from the terminal"
  homepage "https://github.com/avivsinai/bitbucket-cli"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/avivsinai/bitbucket-cli/releases/download/v0.6.0/bkt_0.6.0_darwin_x86_64.tar.gz"
      sha256 "b2a93f91fe3efb2cead26e97af976b8cd51b1a029612dfcbebcf795be679aa91"

      def install
        bin.install "bkt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/avivsinai/bitbucket-cli/releases/download/v0.6.0/bkt_0.6.0_darwin_arm64.tar.gz"
      sha256 "6767f7e01b18ba6c3273abe44a1ea0dbbad0c3ae96282c5a8137571b1046155a"

      def install
        bin.install "bkt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/bitbucket-cli/releases/download/v0.6.0/bkt_0.6.0_linux_x86_64.tar.gz"
      sha256 "c7de3d06498a0b724b788bf48771497247c40120edf80e913301fd59e42f5a08"
      def install
        bin.install "bkt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/bitbucket-cli/releases/download/v0.6.0/bkt_0.6.0_linux_arm64.tar.gz"
      sha256 "53de4b0e8263ab12ff5fdd5d4122b6c780de0adcc8987274072bc75670b48a27"
      def install
        bin.install "bkt"
      end
    end
  end

  test do
    system "#{bin}/bkt", "version"
  end
end
