# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BitbucketCli < Formula
  desc "CLI for Bitbucket Cloud - manage repos, PRs, and pipelines from the terminal"
  homepage "https://github.com/avivsinai/bitbucket-cli"
  version "0.5.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/avivsinai/bitbucket-cli/releases/download/v0.5.4/bkt_0.5.4_darwin_x86_64.tar.gz"
      sha256 "dc7cebb34c9b6ba7fa7cc612713291a9b9ac9c6f8252945ba5e8dde20e8a1f02"

      def install
        bin.install "bkt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/avivsinai/bitbucket-cli/releases/download/v0.5.4/bkt_0.5.4_darwin_arm64.tar.gz"
      sha256 "965284ef9e77905da177889278817413d06845c5837641286569689ade0df752"

      def install
        bin.install "bkt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/bitbucket-cli/releases/download/v0.5.4/bkt_0.5.4_linux_x86_64.tar.gz"
      sha256 "85ec6319ea57cde7b814ef9eee9454615d8c79cae8e72c951216078601f604e2"
      def install
        bin.install "bkt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/bitbucket-cli/releases/download/v0.5.4/bkt_0.5.4_linux_arm64.tar.gz"
      sha256 "093ad088a7a8c3a4ced9e73580dce11edcd788478f6bba0985e770df358591ca"
      def install
        bin.install "bkt"
      end
    end
  end

  test do
    system "#{bin}/bkt", "version"
  end
end
