# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BitbucketCli < Formula
  desc "CLI for Bitbucket Cloud - manage repos, PRs, and pipelines from the terminal"
  homepage "https://github.com/avivsinai/bitbucket-cli"
  version "0.28.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/avivsinai/bitbucket-cli/releases/download/v0.28.2/bkt_0.28.2_darwin_x86_64.tar.gz"
      sha256 "5108fed4a3cb2d6e0506fb72c629e3e5e4089f68af4bc7f1c49ee3f601c1b855"

      define_method(:install) do
        bin.install "bkt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/avivsinai/bitbucket-cli/releases/download/v0.28.2/bkt_0.28.2_darwin_arm64.tar.gz"
      sha256 "b9322b3e0b0989f217764ab8745869d65d893092a0512d5f9afcfe068d78c8d7"

      define_method(:install) do
        bin.install "bkt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/bitbucket-cli/releases/download/v0.28.2/bkt_0.28.2_linux_x86_64.tar.gz"
      sha256 "0a00322702d49897473023b09354c6dd0f59643b6b76dea7961ffd4c91cdcb3b"
      define_method(:install) do
        bin.install "bkt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/bitbucket-cli/releases/download/v0.28.2/bkt_0.28.2_linux_arm64.tar.gz"
      sha256 "c37b6b4d6c73cfe9e63a3f7e23217f7068b643f0181eb6406fb403a77f67024d"
      define_method(:install) do
        bin.install "bkt"
      end
    end
  end

  test do
    system "#{bin}/bkt", "--version"
  end
end
