# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jk < Formula
  desc "CLI for Jenkins - GitHub CLI-style workflows for Jenkins controllers"
  homepage "https://github.com/avivsinai/jenkins-cli"
  version "0.0.28"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/avivsinai/jenkins-cli/releases/download/v0.0.28/jenkins-cli_0.0.28_darwin_x86_64.tar.gz"
      sha256 "9a15d2bac47033d2cf381e023690bfbf430cf4019fcb8c3c5e18b343c37fd688"

      define_method(:install) do
        bin.install "jk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/avivsinai/jenkins-cli/releases/download/v0.0.28/jenkins-cli_0.0.28_darwin_arm64.tar.gz"
      sha256 "33d15eb1e8edd3bff6a1d507ea79c409907d944c0f9217b6122d62f489d0db86"

      define_method(:install) do
        bin.install "jk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/jenkins-cli/releases/download/v0.0.28/jenkins-cli_0.0.28_linux_x86_64.tar.gz"
      sha256 "fc2e5dd9a1be714158f73eb2e685b821c1a32901c665750ea02b22a6ec2e050a"
      define_method(:install) do
        bin.install "jk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/jenkins-cli/releases/download/v0.0.28/jenkins-cli_0.0.28_linux_arm64.tar.gz"
      sha256 "669c8707425b4423bf33634b042e118eed6e2016dafbbee3531939075fd47fbb"
      define_method(:install) do
        bin.install "jk"
      end
    end
  end

  test do
    system "#{bin}/jk", "version"
  end
end
