# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jk < Formula
  desc "CLI for Jenkins - GitHub CLI-style workflows for Jenkins controllers"
  homepage "https://github.com/avivsinai/jenkins-cli"
  version "0.0.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/avivsinai/jenkins-cli/releases/download/v0.0.20/jenkins-cli_0.0.20_darwin_x86_64.tar.gz"
      sha256 "214e1cc0cb53dda189c32f6aefe95cb2a0dc569da2e9eaf331a883107eeb7a20"

      define_method(:install) do
        bin.install "jk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/avivsinai/jenkins-cli/releases/download/v0.0.20/jenkins-cli_0.0.20_darwin_arm64.tar.gz"
      sha256 "462f10dc7de8fe18e54ee222e54f11ff5b4ef5537bde0822d50d8477c2d394e8"

      define_method(:install) do
        bin.install "jk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/jenkins-cli/releases/download/v0.0.20/jenkins-cli_0.0.20_linux_x86_64.tar.gz"
      sha256 "4fd7147be222e9605a67a8c7948425b444b84297eb4b4d5ef5ab1b553bc03523"
      define_method(:install) do
        bin.install "jk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/jenkins-cli/releases/download/v0.0.20/jenkins-cli_0.0.20_linux_arm64.tar.gz"
      sha256 "8424c5e0eed47a6cf51648ab8b95fc7d1915709358c7fcdd05246180a408d764"
      define_method(:install) do
        bin.install "jk"
      end
    end
  end

  test do
    system "#{bin}/jk", "version"
  end
end
